**FLAGS**

Modeli strojnog učenja često zahtjevaju da mnogi parametri budu zadani na početku modela, te da se ti isti parametri po mogućnosti lako mijenjaju, kao što je npr. broj neurona u neuronskoj mreži, *learning rate*, *batch size* itd. Korištenje zastavica (*flags*) je jednostavan način kako bi preko komandne linije mijenjali neki parameter u kodu. Prvi argument je ime zastavice, drugi je zadana vrijednost, a treći opis zastavice.

**MODEL**

Kao arhitektura modela izabrana je LSTM neuronska mreža, posebna vrsta rekurentnih neuronskih mreža koja je dobra za učenje dugotrajnih ovisnosti i pamti informacije u dužem periodu.
Neki od parametara koji su zadani su:

*silence_percentage* – povećavanjem će model raditi u korist *true positive* za *silence* i smanjenjem *false negatives* za riječi

*unknown_percentage* – zadano je da 10% podataka za treniranje bira iz *unknown* klase, povećavanjem će model manje vjerojatno zamijeniti uknown riječi za željene, ali ako je prevelik model će zaključiti da je najsigurnije sve riječi kategorizirati kao uknown

*learning_rate* – zadan je za određeni broj iteracija; kontrolira brzinu ažuriranja težina neuronske mreže

*background_volume*  - glasnoća; 0 je tišina a 1 dokraja pojačana glasnoća

*background_frequency* - u kojoj proporciji je background noise dodan u zvučne zapise 

*batch_size* - broj primjeraka iz uzorka za treniranje u jednoj iteraciji treniranja 

**TRENIRANJE**

Tijekom treniranja vidimo na kojem smo koraku treniranja. Za svakih deset koraka su nam pokazane *accuracy* (točnost) i *cross entropy* vrijednosti. Točnost  nam pokazuje koliko je klasa točno predviđeno na određenom koraku treniranja. Ovaj rezultat često varira, ali se u pravilu povećava kako treniranje mreže ide kraju. *Cross entropy* je rezultat funkcije gubitka, i vrijednost bi trebala padati tijekom treniranja. Nakon svakih 500 koraka dobivamo matricu konfuzije.

import sys
import os
import tensorflow as tf

sys.path.append("../libs")
from classification import input_data
from classification import models
from classification import trainer
from classification import freeze

tf.reset_default_graph()

In [2]:
def del_all_flags(FLAGS):
    flags_dict = FLAGS._flags()
    keys_list = [keys for keys in flags_dict]
    for keys in keys_list:
        FLAGS.__delattr__(keys)





del_all_flags(tf.flags.FLAGS)

In [3]:

flags = tf.app.flags
FLAGS = flags.FLAGS
flags.DEFINE_string('data_dir','../data/raw','Train Data Folder')
flags.DEFINE_string('summaries_dir','../summaries','Summaries Folder')
flags.DEFINE_string('models_dir','../models','Models Folder')
flags.DEFINE_string('wanted_words','yes,no,up,down,left,right,on,off,stop,go','Wanted Words')
flags.DEFINE_float('validation_percentage',10,'Validation Percentage')
flags.DEFINE_float('testing_percentage',10,'Testing Percentage')
flags.DEFINE_integer('sample_rate',16000,'Sample Rate')
flags.DEFINE_integer('clip_duration_ms',1000,'Clip Duration in ms')
flags.DEFINE_float('window_size_ms',40,'How long each spectogram timeslice is')
flags.DEFINE_float('window_stride_ms',20,'How far to move in time between frequency windows.')
flags.DEFINE_integer('dct_coefficient_count',40,'How many bins to use for the MFCC fingerprint')
flags.DEFINE_float('time_shift_ms',100.0,'Range to randomly shift the training audio by in time.')

FLAGS=flags.FLAGS

In [4]:
model_architecture='lstm_l'
logging_interval=10
eval_step_interval=500
save_step_interval=50000
silence_percentage=10.0
unknown_percentage=15.0
background_frequency=1
background_volume=0.3
learning_rate='0.0005,0.0001,0.00002,0.0001,0.00002' 
train_steps='10000,10000,10000,15000,5000' 
batch_size=256


In [5]:
tf.app.flags.DEFINE_string('f', '', 'kernel')
train_dir=os.path.join(FLAGS.data_dir,'train','audio')

In [6]:
model_settings = models.prepare_model_settings(
      len(input_data.prepare_words_list(FLAGS.wanted_words.split(','))),
      FLAGS.sample_rate, FLAGS.clip_duration_ms, FLAGS.window_size_ms,
      FLAGS.window_stride_ms, FLAGS.dct_coefficient_count)
audio_processor = input_data.AudioProcessor(
      train_dir, silence_percentage, unknown_percentage,
      FLAGS.wanted_words.split(','), FLAGS.validation_percentage,
      FLAGS.testing_percentage, model_settings,use_silence_folder=True)

../data/raw\train\audio\*\*.wav
..\data\raw\train\audio\_background_noise_\doing_the_dishes.wav
..\data\raw\train\audio\_background_noise_\dude_miaowing.wav
..\data\raw\train\audio\_background_noise_\exercise_bike.wav
..\data\raw\train\audio\_background_noise_\pink_noise.wav
..\data\raw\train\audio\_background_noise_\running_tap.wav
..\data\raw\train\audio\_background_noise_\white_noise.wav
Tensor("AudioSpectrogram:0", shape=(?, 49, 513), dtype=float32)


In [7]:
def get_train_data(args):
    sess=args
    time_shift_samples = int((FLAGS.time_shift_ms * FLAGS.sample_rate) / 1000)
    train_fingerprints, train_ground_truth = audio_processor.get_data(
        batch_size, 0, model_settings,background_frequency,
        background_volume, time_shift_samples, 'training', sess)
    return train_fingerprints,train_ground_truth

In [8]:
def get_val_data(args):
    '''
    Input: (sess,offset)
    '''
    sess,i=args
    validation_fingerprints, validation_ground_truth = (
            audio_processor.get_data(batch_size, i, model_settings, 0.0,
                                     0.0, 0, 'validation', sess))
    return validation_fingerprints,validation_ground_truth

In [9]:
def get_test_data(args):
    '''
    Input: (sess,offset)
    '''
    sess,i=args
    test_fingerprints, test_ground_truth = audio_processor.get_data(
        batch_size, i, model_settings, 0.0, 0.0, 0, 'testing', sess)
    return test_fingerprints,test_ground_truth

In [10]:
def main(_):
    sess=tf.InteractiveSession()
    # Placeholders
    fingerprint_size = model_settings['fingerprint_size']
    label_count = model_settings['label_count']
    fingerprint_input = tf.placeholder(
      tf.float32, [None, fingerprint_size], name='fingerprint_input')
    ground_truth_input = tf.placeholder(
      tf.float32, [None, label_count], name='groundtruth_input')
    set_size = audio_processor.set_size('validation')
    label_count = model_settings['label_count']
    
    #Model
    
    logits, dropout_prob = models.create_model(
      fingerprint_input,
      model_settings,
      model_architecture,
      is_training=True)
    
    
    extra_args=(dropout_prob,label_count,batch_size,set_size)
    trainer.train(sess,logits,fingerprint_input,ground_truth_input,get_train_data,
                  get_val_data,train_steps,learning_rate,eval_step_interval, logging_interval=logging_interval,
                  checkpoint_interval=save_step_interval,
                  model_name=model_architecture,summaries_dir=FLAGS.summaries_dir,args=extra_args)

In [11]:
tf.app.run(main=main)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

Instructions for updating:
Please switch to tf.train.get_or_create_global_step
INFO:tensorflow:Training from step: 1 
INFO:tensorflow:Step #10: rate 0.000500, accuracy 13.7%, cross entropy 2.418411
INFO:tensorflow:Step #20: rate 0.000500, accuracy 13.7%, cross entropy 2.378950
INFO:tensorflow:Step #30: rate 0.000500, accuracy 13.3%, cross entropy 2.275060
INFO:tensorflow:Step #40: rate 0.000500, accuracy 18.0%, cross entropy 2.271630
INFO:tensorflow:Step #50: rate 0.000500, accuracy 18.0%, cross entropy 2.247811
INFO:tensorflow:Step #60: rate 0.000500, accuracy 20.7%, cross entropy 2.124499
INFO:tensorflow:Step #70: rate 0.000500, accuracy 26.6%, cross entropy 2.069001
INFO:tensorflow:Step #80: rate 0.000500, accuracy 28.5%, cross entropy 2.055431
INFO:tensorflow:Step #90: rate 0.000500, accuracy 

INFO:tensorflow:Step #850: rate 0.000500, accuracy 73.0%, cross entropy 0.838817
INFO:tensorflow:Step #860: rate 0.000500, accuracy 72.7%, cross entropy 0.792592
INFO:tensorflow:Step #870: rate 0.000500, accuracy 69.5%, cross entropy 0.822250
INFO:tensorflow:Step #880: rate 0.000500, accuracy 73.4%, cross entropy 0.785683
INFO:tensorflow:Step #890: rate 0.000500, accuracy 68.0%, cross entropy 0.886864
INFO:tensorflow:Step #900: rate 0.000500, accuracy 77.0%, cross entropy 0.741588
INFO:tensorflow:Step #910: rate 0.000500, accuracy 74.6%, cross entropy 0.777758
INFO:tensorflow:Step #920: rate 0.000500, accuracy 66.8%, cross entropy 0.957895
INFO:tensorflow:Step #930: rate 0.000500, accuracy 71.1%, cross entropy 0.850936
INFO:tensorflow:Step #940: rate 0.000500, accuracy 73.4%, cross entropy 0.832193
INFO:tensorflow:Step #950: rate 0.000500, accuracy 72.3%, cross entropy 0.805397
INFO:tensorflow:Step #960: rate 0.000500, accuracy 73.4%, cross entropy 0.783174
INFO:tensorflow:Step #970: r

INFO:tensorflow:Step #1680: rate 0.000500, accuracy 80.1%, cross entropy 0.604877
INFO:tensorflow:Step #1690: rate 0.000500, accuracy 82.8%, cross entropy 0.591812
INFO:tensorflow:Step #1700: rate 0.000500, accuracy 77.7%, cross entropy 0.713535
INFO:tensorflow:Step #1710: rate 0.000500, accuracy 82.0%, cross entropy 0.503119
INFO:tensorflow:Step #1720: rate 0.000500, accuracy 78.5%, cross entropy 0.595545
INFO:tensorflow:Step #1730: rate 0.000500, accuracy 79.3%, cross entropy 0.527337
INFO:tensorflow:Step #1740: rate 0.000500, accuracy 80.1%, cross entropy 0.628776
INFO:tensorflow:Step #1750: rate 0.000500, accuracy 80.1%, cross entropy 0.597872
INFO:tensorflow:Step #1760: rate 0.000500, accuracy 75.8%, cross entropy 0.673825
INFO:tensorflow:Step #1770: rate 0.000500, accuracy 79.7%, cross entropy 0.628015
INFO:tensorflow:Step #1780: rate 0.000500, accuracy 76.2%, cross entropy 0.723255
INFO:tensorflow:Step #1790: rate 0.000500, accuracy 81.6%, cross entropy 0.511855
INFO:tensorflow:

INFO:tensorflow:Step #2510: rate 0.000500, accuracy 83.6%, cross entropy 0.520651
INFO:tensorflow:Step #2520: rate 0.000500, accuracy 79.3%, cross entropy 0.587951
INFO:tensorflow:Step #2530: rate 0.000500, accuracy 81.6%, cross entropy 0.588253
INFO:tensorflow:Step #2540: rate 0.000500, accuracy 85.2%, cross entropy 0.517748
INFO:tensorflow:Step #2550: rate 0.000500, accuracy 82.8%, cross entropy 0.495371
INFO:tensorflow:Step #2560: rate 0.000500, accuracy 78.9%, cross entropy 0.626962
INFO:tensorflow:Step #2570: rate 0.000500, accuracy 82.0%, cross entropy 0.535267
INFO:tensorflow:Step #2580: rate 0.000500, accuracy 79.7%, cross entropy 0.530213
INFO:tensorflow:Step #2590: rate 0.000500, accuracy 86.7%, cross entropy 0.409292
INFO:tensorflow:Step #2600: rate 0.000500, accuracy 81.2%, cross entropy 0.526605
INFO:tensorflow:Step #2610: rate 0.000500, accuracy 81.2%, cross entropy 0.479779
INFO:tensorflow:Step #2620: rate 0.000500, accuracy 84.8%, cross entropy 0.512703
INFO:tensorflow:

INFO:tensorflow:Step #3430: rate 0.000500, accuracy 82.4%, cross entropy 0.506546
INFO:tensorflow:Step #3440: rate 0.000500, accuracy 81.6%, cross entropy 0.511659
INFO:tensorflow:Step #3450: rate 0.000500, accuracy 84.4%, cross entropy 0.481048
INFO:tensorflow:Step #3460: rate 0.000500, accuracy 85.9%, cross entropy 0.444155
INFO:tensorflow:Step #3470: rate 0.000500, accuracy 82.8%, cross entropy 0.503401
INFO:tensorflow:Step #3480: rate 0.000500, accuracy 82.4%, cross entropy 0.496913
INFO:tensorflow:Step #3490: rate 0.000500, accuracy 85.2%, cross entropy 0.427055
INFO:tensorflow:Step #3500: rate 0.000500, accuracy 84.0%, cross entropy 0.505949
INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 302   6  19   4  11   2   6  16   7   4  10]
 [  0   4 243   5   0   3   4   0   0   0   0   2]
 [  0   8   0 249   1   7   1   0   0   0   0   4]
 [  0   7   0   1 215   1   2   0   3  11  14   6]
 [  0   1   1   8   0 247   0   0   0   0   2   5]
 [ 

INFO:tensorflow:Step #4260: rate 0.000500, accuracy 84.0%, cross entropy 0.438972
INFO:tensorflow:Step #4270: rate 0.000500, accuracy 86.3%, cross entropy 0.386565
INFO:tensorflow:Step #4280: rate 0.000500, accuracy 88.3%, cross entropy 0.394856
INFO:tensorflow:Step #4290: rate 0.000500, accuracy 80.9%, cross entropy 0.512873
INFO:tensorflow:Step #4300: rate 0.000500, accuracy 85.9%, cross entropy 0.428115
INFO:tensorflow:Step #4310: rate 0.000500, accuracy 81.2%, cross entropy 0.557348
INFO:tensorflow:Step #4320: rate 0.000500, accuracy 83.6%, cross entropy 0.496599
INFO:tensorflow:Step #4330: rate 0.000500, accuracy 84.0%, cross entropy 0.454952
INFO:tensorflow:Step #4340: rate 0.000500, accuracy 88.3%, cross entropy 0.312896
INFO:tensorflow:Step #4350: rate 0.000500, accuracy 84.4%, cross entropy 0.396008
INFO:tensorflow:Step #4360: rate 0.000500, accuracy 86.7%, cross entropy 0.411118
INFO:tensorflow:Step #4370: rate 0.000500, accuracy 84.8%, cross entropy 0.412536
INFO:tensorflow:

INFO:tensorflow:Step #5090: rate 0.000500, accuracy 83.2%, cross entropy 0.423372
INFO:tensorflow:Step #5100: rate 0.000500, accuracy 85.2%, cross entropy 0.413938
INFO:tensorflow:Step #5110: rate 0.000500, accuracy 86.7%, cross entropy 0.385653
INFO:tensorflow:Step #5120: rate 0.000500, accuracy 83.6%, cross entropy 0.480993
INFO:tensorflow:Step #5130: rate 0.000500, accuracy 84.8%, cross entropy 0.404327
INFO:tensorflow:Step #5140: rate 0.000500, accuracy 87.5%, cross entropy 0.373884
INFO:tensorflow:Step #5150: rate 0.000500, accuracy 83.6%, cross entropy 0.480495
INFO:tensorflow:Step #5160: rate 0.000500, accuracy 84.4%, cross entropy 0.446325
INFO:tensorflow:Step #5170: rate 0.000500, accuracy 82.4%, cross entropy 0.543335
INFO:tensorflow:Step #5180: rate 0.000500, accuracy 86.3%, cross entropy 0.377882
INFO:tensorflow:Step #5190: rate 0.000500, accuracy 83.2%, cross entropy 0.465937
INFO:tensorflow:Step #5200: rate 0.000500, accuracy 90.2%, cross entropy 0.287657
INFO:tensorflow:

INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 326   2  13   3   8   3   5   9   6   1  11]
 [  0   8 237   5   0   0   6   0   2   0   0   3]
 [  0  11   0 253   0   3   0   1   0   0   0   2]
 [  0   5   0   2 212   4   1   1   3  12  19   1]
 [  0   3   0  11   0 246   0   0   0   0   1   3]
 [  0   6   4   5   0   1 229   0   2   0   0   0]
 [  0  20   0   2   0   0   0 231   3   0   0   0]
 [  0  15   0   0   2   0   0   0 238   2   0   0]
 [  0   6   0   0  10   0   0   2   4 227   6   1]
 [  0   8   0   1   3   8   1   0   0   2 222   1]
 [  0  12   1  23   0   8   0   0   1   1   1 213]]
INFO:tensorflow:Step 6000: Validation accuracy = 88.9% (N=2964)
INFO:tensorflow:Step #6010: rate 0.000500, accuracy 82.4%, cross entropy 0.475520
INFO:tensorflow:Step #6020: rate 0.000500, accuracy 87.1%, cross entropy 0.399136
INFO:tensorflow:Step #6030: rate 0.000500, accuracy 89.8%, cross entropy 0.296213
INFO:tensorflow:Step #6040: rate 0.000500,

INFO:tensorflow:Step #6840: rate 0.000500, accuracy 84.4%, cross entropy 0.455797
INFO:tensorflow:Step #6850: rate 0.000500, accuracy 85.9%, cross entropy 0.373973
INFO:tensorflow:Step #6860: rate 0.000500, accuracy 83.6%, cross entropy 0.414577
INFO:tensorflow:Step #6870: rate 0.000500, accuracy 92.2%, cross entropy 0.234850
INFO:tensorflow:Step #6880: rate 0.000500, accuracy 89.8%, cross entropy 0.269060
INFO:tensorflow:Step #6890: rate 0.000500, accuracy 87.1%, cross entropy 0.360640
INFO:tensorflow:Step #6900: rate 0.000500, accuracy 87.9%, cross entropy 0.380606
INFO:tensorflow:Step #6910: rate 0.000500, accuracy 86.3%, cross entropy 0.353180
INFO:tensorflow:Step #6920: rate 0.000500, accuracy 88.3%, cross entropy 0.315248
INFO:tensorflow:Step #6930: rate 0.000500, accuracy 88.3%, cross entropy 0.324880
INFO:tensorflow:Step #6940: rate 0.000500, accuracy 86.7%, cross entropy 0.384549
INFO:tensorflow:Step #6950: rate 0.000500, accuracy 86.7%, cross entropy 0.374176
INFO:tensorflow:

INFO:tensorflow:Step #7670: rate 0.000500, accuracy 88.3%, cross entropy 0.345994
INFO:tensorflow:Step #7680: rate 0.000500, accuracy 87.5%, cross entropy 0.386585
INFO:tensorflow:Step #7690: rate 0.000500, accuracy 88.3%, cross entropy 0.344625
INFO:tensorflow:Step #7700: rate 0.000500, accuracy 84.8%, cross entropy 0.393551
INFO:tensorflow:Step #7710: rate 0.000500, accuracy 91.0%, cross entropy 0.289840
INFO:tensorflow:Step #7720: rate 0.000500, accuracy 87.1%, cross entropy 0.384857
INFO:tensorflow:Step #7730: rate 0.000500, accuracy 84.4%, cross entropy 0.459711
INFO:tensorflow:Step #7740: rate 0.000500, accuracy 89.5%, cross entropy 0.324789
INFO:tensorflow:Step #7750: rate 0.000500, accuracy 84.8%, cross entropy 0.413985
INFO:tensorflow:Step #7760: rate 0.000500, accuracy 88.7%, cross entropy 0.391940
INFO:tensorflow:Step #7770: rate 0.000500, accuracy 86.3%, cross entropy 0.394320
INFO:tensorflow:Step #7780: rate 0.000500, accuracy 87.5%, cross entropy 0.328883
INFO:tensorflow:

INFO:tensorflow:Step 8500: Validation accuracy = 88.7% (N=2964)
INFO:tensorflow:Step #8510: rate 0.000500, accuracy 91.8%, cross entropy 0.236099
INFO:tensorflow:Step #8520: rate 0.000500, accuracy 87.5%, cross entropy 0.327350
INFO:tensorflow:Step #8530: rate 0.000500, accuracy 87.5%, cross entropy 0.345340
INFO:tensorflow:Step #8540: rate 0.000500, accuracy 85.5%, cross entropy 0.404909
INFO:tensorflow:Step #8550: rate 0.000500, accuracy 91.4%, cross entropy 0.274273
INFO:tensorflow:Step #8560: rate 0.000500, accuracy 91.8%, cross entropy 0.287014
INFO:tensorflow:Step #8570: rate 0.000500, accuracy 88.3%, cross entropy 0.332772
INFO:tensorflow:Step #8580: rate 0.000500, accuracy 92.2%, cross entropy 0.232299
INFO:tensorflow:Step #8590: rate 0.000500, accuracy 88.7%, cross entropy 0.343594
INFO:tensorflow:Step #8600: rate 0.000500, accuracy 86.7%, cross entropy 0.391439
INFO:tensorflow:Step #8610: rate 0.000500, accuracy 87.5%, cross entropy 0.434379
INFO:tensorflow:Step #8620: rate 0

INFO:tensorflow:Step #9420: rate 0.000500, accuracy 86.3%, cross entropy 0.391127
INFO:tensorflow:Step #9430: rate 0.000500, accuracy 91.4%, cross entropy 0.267580
INFO:tensorflow:Step #9440: rate 0.000500, accuracy 87.9%, cross entropy 0.329017
INFO:tensorflow:Step #9450: rate 0.000500, accuracy 90.6%, cross entropy 0.265122
INFO:tensorflow:Step #9460: rate 0.000500, accuracy 91.4%, cross entropy 0.318805
INFO:tensorflow:Step #9470: rate 0.000500, accuracy 89.8%, cross entropy 0.284786
INFO:tensorflow:Step #9480: rate 0.000500, accuracy 87.1%, cross entropy 0.391805
INFO:tensorflow:Step #9490: rate 0.000500, accuracy 89.1%, cross entropy 0.317629
INFO:tensorflow:Step #9500: rate 0.000500, accuracy 85.5%, cross entropy 0.397365
INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 304   6  20   1   9   3   4  14  10   7   9]
 [  0   4 244   3   2   0   5   0   0   1   0   2]
 [  0   7   1 254   0   1   0   0   0   0   1   6]
 [  0   3   0   3 202  

INFO:tensorflow:Step #10250: rate 0.000100, accuracy 89.5%, cross entropy 0.287706
INFO:tensorflow:Step #10260: rate 0.000100, accuracy 88.3%, cross entropy 0.340858
INFO:tensorflow:Step #10270: rate 0.000100, accuracy 88.7%, cross entropy 0.305684
INFO:tensorflow:Step #10280: rate 0.000100, accuracy 89.5%, cross entropy 0.288587
INFO:tensorflow:Step #10290: rate 0.000100, accuracy 89.5%, cross entropy 0.246172
INFO:tensorflow:Step #10300: rate 0.000100, accuracy 89.5%, cross entropy 0.318210
INFO:tensorflow:Step #10310: rate 0.000100, accuracy 92.6%, cross entropy 0.255976
INFO:tensorflow:Step #10320: rate 0.000100, accuracy 92.2%, cross entropy 0.261570
INFO:tensorflow:Step #10330: rate 0.000100, accuracy 89.8%, cross entropy 0.273387
INFO:tensorflow:Step #10340: rate 0.000100, accuracy 87.5%, cross entropy 0.352158
INFO:tensorflow:Step #10350: rate 0.000100, accuracy 93.4%, cross entropy 0.222116
INFO:tensorflow:Step #10360: rate 0.000100, accuracy 91.4%, cross entropy 0.261662
INFO

INFO:tensorflow:Step #11070: rate 0.000100, accuracy 90.2%, cross entropy 0.268888
INFO:tensorflow:Step #11080: rate 0.000100, accuracy 91.0%, cross entropy 0.255782
INFO:tensorflow:Step #11090: rate 0.000100, accuracy 90.6%, cross entropy 0.318538
INFO:tensorflow:Step #11100: rate 0.000100, accuracy 91.4%, cross entropy 0.246365
INFO:tensorflow:Step #11110: rate 0.000100, accuracy 91.0%, cross entropy 0.250247
INFO:tensorflow:Step #11120: rate 0.000100, accuracy 90.2%, cross entropy 0.291588
INFO:tensorflow:Step #11130: rate 0.000100, accuracy 93.8%, cross entropy 0.231707
INFO:tensorflow:Step #11140: rate 0.000100, accuracy 89.1%, cross entropy 0.254324
INFO:tensorflow:Step #11150: rate 0.000100, accuracy 89.1%, cross entropy 0.304073
INFO:tensorflow:Step #11160: rate 0.000100, accuracy 89.1%, cross entropy 0.291191
INFO:tensorflow:Step #11170: rate 0.000100, accuracy 93.0%, cross entropy 0.238757
INFO:tensorflow:Step #11180: rate 0.000100, accuracy 83.6%, cross entropy 0.408318
INFO

INFO:tensorflow:Step #11980: rate 0.000100, accuracy 90.2%, cross entropy 0.285986
INFO:tensorflow:Step #11990: rate 0.000100, accuracy 88.7%, cross entropy 0.326442
INFO:tensorflow:Step #12000: rate 0.000100, accuracy 90.2%, cross entropy 0.299238
INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 329   5   9   2   7   2   4  12   5   2  10]
 [  0   4 238   4   3   0  10   0   0   0   0   2]
 [  0   8   0 258   0   0   0   1   1   0   0   2]
 [  0   4   0   2 220   0   3   0   3  22   3   3]
 [  0   1   0  12   0 245   0   0   0   0   1   5]
 [  0   1   3   2   1   1 237   0   2   0   0   0]
 [  0  12   0   0   2   0   2 237   3   0   0   0]
 [  0  11   0   0   5   1   0   0 238   2   0   0]
 [  0   1   0   0  12   0   1   1  15 225   0   1]
 [  0   8   0   2   5   3   2   0   0   2 221   3]
 [  0   6   0  21   6   4   1   0   3   2   1 216]]
INFO:tensorflow:Step 12000: Validation accuracy = 89.9% (N=2964)
INFO:tensorflow:Step #12010: rate 0.00

INFO:tensorflow:Step #12800: rate 0.000100, accuracy 94.5%, cross entropy 0.193153
INFO:tensorflow:Step #12810: rate 0.000100, accuracy 89.8%, cross entropy 0.286624
INFO:tensorflow:Step #12820: rate 0.000100, accuracy 89.5%, cross entropy 0.269341
INFO:tensorflow:Step #12830: rate 0.000100, accuracy 92.2%, cross entropy 0.252596
INFO:tensorflow:Step #12840: rate 0.000100, accuracy 92.2%, cross entropy 0.227529
INFO:tensorflow:Step #12850: rate 0.000100, accuracy 93.0%, cross entropy 0.249769
INFO:tensorflow:Step #12860: rate 0.000100, accuracy 91.4%, cross entropy 0.216913
INFO:tensorflow:Step #12870: rate 0.000100, accuracy 85.2%, cross entropy 0.384677
INFO:tensorflow:Step #12880: rate 0.000100, accuracy 90.2%, cross entropy 0.265907
INFO:tensorflow:Step #12890: rate 0.000100, accuracy 91.8%, cross entropy 0.214110
INFO:tensorflow:Step #12900: rate 0.000100, accuracy 91.0%, cross entropy 0.265353
INFO:tensorflow:Step #12910: rate 0.000100, accuracy 89.5%, cross entropy 0.273888
INFO

INFO:tensorflow:Step #13620: rate 0.000100, accuracy 88.3%, cross entropy 0.298250
INFO:tensorflow:Step #13630: rate 0.000100, accuracy 90.6%, cross entropy 0.249255
INFO:tensorflow:Step #13640: rate 0.000100, accuracy 93.8%, cross entropy 0.231886
INFO:tensorflow:Step #13650: rate 0.000100, accuracy 91.8%, cross entropy 0.258921
INFO:tensorflow:Step #13660: rate 0.000100, accuracy 91.0%, cross entropy 0.283443
INFO:tensorflow:Step #13670: rate 0.000100, accuracy 93.0%, cross entropy 0.232599
INFO:tensorflow:Step #13680: rate 0.000100, accuracy 89.8%, cross entropy 0.280617
INFO:tensorflow:Step #13690: rate 0.000100, accuracy 92.2%, cross entropy 0.245857
INFO:tensorflow:Step #13700: rate 0.000100, accuracy 92.2%, cross entropy 0.238587
INFO:tensorflow:Step #13710: rate 0.000100, accuracy 90.6%, cross entropy 0.331837
INFO:tensorflow:Step #13720: rate 0.000100, accuracy 91.4%, cross entropy 0.250002
INFO:tensorflow:Step #13730: rate 0.000100, accuracy 90.2%, cross entropy 0.265620
INFO

INFO:tensorflow:Step 14500: Validation accuracy = 89.5% (N=2964)
INFO:tensorflow:Step #14510: rate 0.000100, accuracy 91.0%, cross entropy 0.205520
INFO:tensorflow:Step #14520: rate 0.000100, accuracy 88.3%, cross entropy 0.326040
INFO:tensorflow:Step #14530: rate 0.000100, accuracy 89.8%, cross entropy 0.257842
INFO:tensorflow:Step #14540: rate 0.000100, accuracy 88.7%, cross entropy 0.335410
INFO:tensorflow:Step #14550: rate 0.000100, accuracy 93.0%, cross entropy 0.225831
INFO:tensorflow:Step #14560: rate 0.000100, accuracy 91.0%, cross entropy 0.249659
INFO:tensorflow:Step #14570: rate 0.000100, accuracy 93.4%, cross entropy 0.203970
INFO:tensorflow:Step #14580: rate 0.000100, accuracy 93.8%, cross entropy 0.235414
INFO:tensorflow:Step #14590: rate 0.000100, accuracy 92.6%, cross entropy 0.213935
INFO:tensorflow:Step #14600: rate 0.000100, accuracy 90.6%, cross entropy 0.237037
INFO:tensorflow:Step #14610: rate 0.000100, accuracy 92.2%, cross entropy 0.247016
INFO:tensorflow:Step #

INFO:tensorflow:Step #15410: rate 0.000100, accuracy 89.5%, cross entropy 0.295799
INFO:tensorflow:Step #15420: rate 0.000100, accuracy 90.6%, cross entropy 0.263897
INFO:tensorflow:Step #15430: rate 0.000100, accuracy 88.7%, cross entropy 0.312710
INFO:tensorflow:Step #15440: rate 0.000100, accuracy 91.8%, cross entropy 0.238179
INFO:tensorflow:Step #15450: rate 0.000100, accuracy 89.5%, cross entropy 0.248342
INFO:tensorflow:Step #15460: rate 0.000100, accuracy 94.1%, cross entropy 0.192197
INFO:tensorflow:Step #15470: rate 0.000100, accuracy 90.2%, cross entropy 0.256340
INFO:tensorflow:Step #15480: rate 0.000100, accuracy 90.6%, cross entropy 0.246367
INFO:tensorflow:Step #15490: rate 0.000100, accuracy 91.8%, cross entropy 0.222132
INFO:tensorflow:Step #15500: rate 0.000100, accuracy 89.1%, cross entropy 0.375987
INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 314   7  11   1   3   3   4  13   6   3  22]
 [  0   3 241   4   2   1   7   0

INFO:tensorflow:Step #16230: rate 0.000100, accuracy 90.2%, cross entropy 0.277059
INFO:tensorflow:Step #16240: rate 0.000100, accuracy 89.8%, cross entropy 0.289568
INFO:tensorflow:Step #16250: rate 0.000100, accuracy 91.0%, cross entropy 0.283024
INFO:tensorflow:Step #16260: rate 0.000100, accuracy 91.8%, cross entropy 0.295886
INFO:tensorflow:Step #16270: rate 0.000100, accuracy 91.8%, cross entropy 0.245462
INFO:tensorflow:Step #16280: rate 0.000100, accuracy 90.2%, cross entropy 0.251834
INFO:tensorflow:Step #16290: rate 0.000100, accuracy 91.4%, cross entropy 0.252696
INFO:tensorflow:Step #16300: rate 0.000100, accuracy 91.0%, cross entropy 0.259808
INFO:tensorflow:Step #16310: rate 0.000100, accuracy 90.2%, cross entropy 0.309906
INFO:tensorflow:Step #16320: rate 0.000100, accuracy 94.1%, cross entropy 0.205405
INFO:tensorflow:Step #16330: rate 0.000100, accuracy 95.7%, cross entropy 0.138349
INFO:tensorflow:Step #16340: rate 0.000100, accuracy 91.8%, cross entropy 0.257583
INFO

INFO:tensorflow:Step #17050: rate 0.000100, accuracy 89.5%, cross entropy 0.334946
INFO:tensorflow:Step #17060: rate 0.000100, accuracy 88.3%, cross entropy 0.337461
INFO:tensorflow:Step #17070: rate 0.000100, accuracy 92.2%, cross entropy 0.254665
INFO:tensorflow:Step #17080: rate 0.000100, accuracy 94.1%, cross entropy 0.149687
INFO:tensorflow:Step #17090: rate 0.000100, accuracy 91.0%, cross entropy 0.270530
INFO:tensorflow:Step #17100: rate 0.000100, accuracy 89.5%, cross entropy 0.276150
INFO:tensorflow:Step #17110: rate 0.000100, accuracy 91.8%, cross entropy 0.264370
INFO:tensorflow:Step #17120: rate 0.000100, accuracy 93.8%, cross entropy 0.200881
INFO:tensorflow:Step #17130: rate 0.000100, accuracy 92.6%, cross entropy 0.237013
INFO:tensorflow:Step #17140: rate 0.000100, accuracy 91.4%, cross entropy 0.239865
INFO:tensorflow:Step #17150: rate 0.000100, accuracy 93.4%, cross entropy 0.197938
INFO:tensorflow:Step #17160: rate 0.000100, accuracy 91.4%, cross entropy 0.263520
INFO

INFO:tensorflow:Step #17960: rate 0.000100, accuracy 91.8%, cross entropy 0.215976
INFO:tensorflow:Step #17970: rate 0.000100, accuracy 87.1%, cross entropy 0.329701
INFO:tensorflow:Step #17980: rate 0.000100, accuracy 89.8%, cross entropy 0.280577
INFO:tensorflow:Step #17990: rate 0.000100, accuracy 88.7%, cross entropy 0.292666
INFO:tensorflow:Step #18000: rate 0.000100, accuracy 92.2%, cross entropy 0.239785
INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 321   4  15   4   6   1   5  11   6   3  11]
 [  0   2 237   5   3   1  10   1   0   0   0   2]
 [  0   8   0 256   0   0   0   1   1   0   1   3]
 [  0   2   0   3 207   0   5   0   3  31   4   5]
 [  0   2   0  10   0 246   0   0   0   0   1   5]
 [  0   1   5   3   1   1 233   0   2   1   0   0]
 [  0  10   0   0   2   1   2 232   9   0   0   0]
 [  0   4   0   0   5   0   0   0 246   2   0   0]
 [  0   1   0   0   7   0   1   1  10 236   0   0]
 [  0   5   0   1   5   4   3   0   0   

INFO:tensorflow:Step #18780: rate 0.000100, accuracy 93.4%, cross entropy 0.214718
INFO:tensorflow:Step #18790: rate 0.000100, accuracy 93.4%, cross entropy 0.205757
INFO:tensorflow:Step #18800: rate 0.000100, accuracy 90.2%, cross entropy 0.282600
INFO:tensorflow:Step #18810: rate 0.000100, accuracy 90.2%, cross entropy 0.287911
INFO:tensorflow:Step #18820: rate 0.000100, accuracy 92.6%, cross entropy 0.218957
INFO:tensorflow:Step #18830: rate 0.000100, accuracy 89.8%, cross entropy 0.271521
INFO:tensorflow:Step #18840: rate 0.000100, accuracy 94.9%, cross entropy 0.173058
INFO:tensorflow:Step #18850: rate 0.000100, accuracy 88.3%, cross entropy 0.261511
INFO:tensorflow:Step #18860: rate 0.000100, accuracy 91.4%, cross entropy 0.227848
INFO:tensorflow:Step #18870: rate 0.000100, accuracy 93.0%, cross entropy 0.227462
INFO:tensorflow:Step #18880: rate 0.000100, accuracy 91.4%, cross entropy 0.248459
INFO:tensorflow:Step #18890: rate 0.000100, accuracy 87.1%, cross entropy 0.339156
INFO

INFO:tensorflow:Step #19600: rate 0.000100, accuracy 92.6%, cross entropy 0.237234
INFO:tensorflow:Step #19610: rate 0.000100, accuracy 94.5%, cross entropy 0.165104
INFO:tensorflow:Step #19620: rate 0.000100, accuracy 93.0%, cross entropy 0.217408
INFO:tensorflow:Step #19630: rate 0.000100, accuracy 88.3%, cross entropy 0.309078
INFO:tensorflow:Step #19640: rate 0.000100, accuracy 89.5%, cross entropy 0.283992
INFO:tensorflow:Step #19650: rate 0.000100, accuracy 90.6%, cross entropy 0.317849
INFO:tensorflow:Step #19660: rate 0.000100, accuracy 89.8%, cross entropy 0.253139
INFO:tensorflow:Step #19670: rate 0.000100, accuracy 95.7%, cross entropy 0.117164
INFO:tensorflow:Step #19680: rate 0.000100, accuracy 91.4%, cross entropy 0.242449
INFO:tensorflow:Step #19690: rate 0.000100, accuracy 90.2%, cross entropy 0.241351
INFO:tensorflow:Step #19700: rate 0.000100, accuracy 94.9%, cross entropy 0.188420
INFO:tensorflow:Step #19710: rate 0.000100, accuracy 85.9%, cross entropy 0.373776
INFO

INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 324   5  16   4   3   2   3  12   6   2  10]
 [  0   3 239   4   3   1   8   0   0   0   0   3]
 [  0   9   0 255   0   0   0   1   1   0   1   3]
 [  0   3   0   1 217   0   5   0   3  20   4   7]
 [  0   3   0  10   0 245   0   0   0   0   1   5]
 [  0   0   6   4   1   1 232   0   2   1   0   0]
 [  0  13   0   0   2   0   1 234   6   0   0   0]
 [  0   7   0   1   4   1   0   0 241   3   0   0]
 [  0   1   0   0   9   0   1   0  10 235   0   0]
 [  0   9   0   2   5   5   2   0   0   3 218   2]
 [  0   8   0  24   5   7   0   0   3   1   0 212]]
INFO:tensorflow:Step 20500: Validation accuracy = 89.5% (N=2964)
INFO:tensorflow:Step #20510: rate 0.000020, accuracy 93.4%, cross entropy 0.196733
INFO:tensorflow:Step #20520: rate 0.000020, accuracy 92.6%, cross entropy 0.217455
INFO:tensorflow:Step #20530: rate 0.000020, accuracy 93.8%, cross entropy 0.169833
INFO:tensorflow:Step #20540: rate 0.00

INFO:tensorflow:Step #21330: rate 0.000020, accuracy 89.5%, cross entropy 0.286483
INFO:tensorflow:Step #21340: rate 0.000020, accuracy 89.5%, cross entropy 0.264039
INFO:tensorflow:Step #21350: rate 0.000020, accuracy 94.9%, cross entropy 0.204177
INFO:tensorflow:Step #21360: rate 0.000020, accuracy 92.6%, cross entropy 0.230283
INFO:tensorflow:Step #21370: rate 0.000020, accuracy 90.2%, cross entropy 0.267175
INFO:tensorflow:Step #21380: rate 0.000020, accuracy 91.4%, cross entropy 0.243183
INFO:tensorflow:Step #21390: rate 0.000020, accuracy 91.4%, cross entropy 0.234335
INFO:tensorflow:Step #21400: rate 0.000020, accuracy 93.0%, cross entropy 0.165599
INFO:tensorflow:Step #21410: rate 0.000020, accuracy 93.4%, cross entropy 0.186617
INFO:tensorflow:Step #21420: rate 0.000020, accuracy 89.5%, cross entropy 0.274922
INFO:tensorflow:Step #21430: rate 0.000020, accuracy 89.5%, cross entropy 0.294676
INFO:tensorflow:Step #21440: rate 0.000020, accuracy 89.8%, cross entropy 0.269184
INFO

INFO:tensorflow:Step #22150: rate 0.000020, accuracy 93.0%, cross entropy 0.216115
INFO:tensorflow:Step #22160: rate 0.000020, accuracy 94.9%, cross entropy 0.178119
INFO:tensorflow:Step #22170: rate 0.000020, accuracy 93.4%, cross entropy 0.219005
INFO:tensorflow:Step #22180: rate 0.000020, accuracy 93.4%, cross entropy 0.228637
INFO:tensorflow:Step #22190: rate 0.000020, accuracy 93.0%, cross entropy 0.210808
INFO:tensorflow:Step #22200: rate 0.000020, accuracy 93.8%, cross entropy 0.220393
INFO:tensorflow:Step #22210: rate 0.000020, accuracy 91.8%, cross entropy 0.255047
INFO:tensorflow:Step #22220: rate 0.000020, accuracy 90.6%, cross entropy 0.264393
INFO:tensorflow:Step #22230: rate 0.000020, accuracy 93.0%, cross entropy 0.203274
INFO:tensorflow:Step #22240: rate 0.000020, accuracy 89.8%, cross entropy 0.284241
INFO:tensorflow:Step #22250: rate 0.000020, accuracy 87.5%, cross entropy 0.309573
INFO:tensorflow:Step #22260: rate 0.000020, accuracy 94.1%, cross entropy 0.184839
INFO

INFO:tensorflow:Step 23000: Validation accuracy = 89.8% (N=2964)
INFO:tensorflow:Step #23010: rate 0.000020, accuracy 92.6%, cross entropy 0.198685
INFO:tensorflow:Step #23020: rate 0.000020, accuracy 94.1%, cross entropy 0.195966
INFO:tensorflow:Step #23030: rate 0.000020, accuracy 93.0%, cross entropy 0.228052
INFO:tensorflow:Step #23040: rate 0.000020, accuracy 93.0%, cross entropy 0.246270
INFO:tensorflow:Step #23050: rate 0.000020, accuracy 92.6%, cross entropy 0.199939
INFO:tensorflow:Step #23060: rate 0.000020, accuracy 94.9%, cross entropy 0.180749
INFO:tensorflow:Step #23070: rate 0.000020, accuracy 90.6%, cross entropy 0.271883
INFO:tensorflow:Step #23080: rate 0.000020, accuracy 90.2%, cross entropy 0.236334
INFO:tensorflow:Step #23090: rate 0.000020, accuracy 93.0%, cross entropy 0.270737
INFO:tensorflow:Step #23100: rate 0.000020, accuracy 92.2%, cross entropy 0.243286
INFO:tensorflow:Step #23110: rate 0.000020, accuracy 92.2%, cross entropy 0.232501
INFO:tensorflow:Step #

INFO:tensorflow:Step #23910: rate 0.000020, accuracy 91.8%, cross entropy 0.254470
INFO:tensorflow:Step #23920: rate 0.000020, accuracy 94.9%, cross entropy 0.187152
INFO:tensorflow:Step #23930: rate 0.000020, accuracy 88.3%, cross entropy 0.314221
INFO:tensorflow:Step #23940: rate 0.000020, accuracy 91.8%, cross entropy 0.221315
INFO:tensorflow:Step #23950: rate 0.000020, accuracy 91.8%, cross entropy 0.238383
INFO:tensorflow:Step #23960: rate 0.000020, accuracy 91.8%, cross entropy 0.230281
INFO:tensorflow:Step #23970: rate 0.000020, accuracy 90.6%, cross entropy 0.263746
INFO:tensorflow:Step #23980: rate 0.000020, accuracy 92.2%, cross entropy 0.261943
INFO:tensorflow:Step #23990: rate 0.000020, accuracy 93.0%, cross entropy 0.177118
INFO:tensorflow:Step #24000: rate 0.000020, accuracy 93.8%, cross entropy 0.196184
INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 324   5  14   4   4   1   3  12   6   2  12]
 [  0   3 242   4   3   1   6   0

INFO:tensorflow:Step #24730: rate 0.000020, accuracy 95.3%, cross entropy 0.180288
INFO:tensorflow:Step #24740: rate 0.000020, accuracy 92.6%, cross entropy 0.206595
INFO:tensorflow:Step #24750: rate 0.000020, accuracy 87.5%, cross entropy 0.311517
INFO:tensorflow:Step #24760: rate 0.000020, accuracy 92.6%, cross entropy 0.246958
INFO:tensorflow:Step #24770: rate 0.000020, accuracy 92.6%, cross entropy 0.219437
INFO:tensorflow:Step #24780: rate 0.000020, accuracy 92.6%, cross entropy 0.191609
INFO:tensorflow:Step #24790: rate 0.000020, accuracy 93.0%, cross entropy 0.237888
INFO:tensorflow:Step #24800: rate 0.000020, accuracy 92.6%, cross entropy 0.227040
INFO:tensorflow:Step #24810: rate 0.000020, accuracy 89.1%, cross entropy 0.283361
INFO:tensorflow:Step #24820: rate 0.000020, accuracy 91.0%, cross entropy 0.248618
INFO:tensorflow:Step #24830: rate 0.000020, accuracy 91.8%, cross entropy 0.229729
INFO:tensorflow:Step #24840: rate 0.000020, accuracy 87.5%, cross entropy 0.406451
INFO

INFO:tensorflow:Step #25550: rate 0.000020, accuracy 88.3%, cross entropy 0.340938
INFO:tensorflow:Step #25560: rate 0.000020, accuracy 93.4%, cross entropy 0.194092
INFO:tensorflow:Step #25570: rate 0.000020, accuracy 91.8%, cross entropy 0.214573
INFO:tensorflow:Step #25580: rate 0.000020, accuracy 91.0%, cross entropy 0.235736
INFO:tensorflow:Step #25590: rate 0.000020, accuracy 89.8%, cross entropy 0.264694
INFO:tensorflow:Step #25600: rate 0.000020, accuracy 92.6%, cross entropy 0.159335
INFO:tensorflow:Step #25610: rate 0.000020, accuracy 93.8%, cross entropy 0.181601
INFO:tensorflow:Step #25620: rate 0.000020, accuracy 90.2%, cross entropy 0.257673
INFO:tensorflow:Step #25630: rate 0.000020, accuracy 92.2%, cross entropy 0.175629
INFO:tensorflow:Step #25640: rate 0.000020, accuracy 92.2%, cross entropy 0.214789
INFO:tensorflow:Step #25650: rate 0.000020, accuracy 92.2%, cross entropy 0.202377
INFO:tensorflow:Step #25660: rate 0.000020, accuracy 92.2%, cross entropy 0.227981
INFO

INFO:tensorflow:Step #26460: rate 0.000020, accuracy 89.1%, cross entropy 0.345920
INFO:tensorflow:Step #26470: rate 0.000020, accuracy 94.1%, cross entropy 0.166995
INFO:tensorflow:Step #26480: rate 0.000020, accuracy 91.4%, cross entropy 0.256727
INFO:tensorflow:Step #26490: rate 0.000020, accuracy 91.8%, cross entropy 0.264691
INFO:tensorflow:Step #26500: rate 0.000020, accuracy 91.8%, cross entropy 0.213435
INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 325   6  13   2   4   1   3  12   6   2  13]
 [  0   3 241   4   3   1   7   0   0   0   0   2]
 [  0   9   0 254   0   0   0   1   1   0   1   4]
 [  0   3   0   2 212   1   5   0   2  24   3   8]
 [  0   2   0  12   0 245   0   0   0   0   1   4]
 [  0   0   5   4   1   1 233   0   2   1   0   0]
 [  0  13   0   0   4   0   3 229   7   0   0   0]
 [  0   6   0   0   5   1   0   0 242   3   0   0]
 [  0   1   0   0  12   0   1   0  12 230   0   0]
 [  0   8   0   2   5   4   2   0   0   

INFO:tensorflow:Step #27280: rate 0.000020, accuracy 91.8%, cross entropy 0.280907
INFO:tensorflow:Step #27290: rate 0.000020, accuracy 95.3%, cross entropy 0.153203
INFO:tensorflow:Step #27300: rate 0.000020, accuracy 92.6%, cross entropy 0.218944
INFO:tensorflow:Step #27310: rate 0.000020, accuracy 92.6%, cross entropy 0.206187
INFO:tensorflow:Step #27320: rate 0.000020, accuracy 93.8%, cross entropy 0.222809
INFO:tensorflow:Step #27330: rate 0.000020, accuracy 93.0%, cross entropy 0.244567
INFO:tensorflow:Step #27340: rate 0.000020, accuracy 92.2%, cross entropy 0.249573
INFO:tensorflow:Step #27350: rate 0.000020, accuracy 92.2%, cross entropy 0.226151
INFO:tensorflow:Step #27360: rate 0.000020, accuracy 93.0%, cross entropy 0.199067
INFO:tensorflow:Step #27370: rate 0.000020, accuracy 90.2%, cross entropy 0.277317
INFO:tensorflow:Step #27380: rate 0.000020, accuracy 91.0%, cross entropy 0.239603
INFO:tensorflow:Step #27390: rate 0.000020, accuracy 89.1%, cross entropy 0.284132
INFO

INFO:tensorflow:Step #28100: rate 0.000020, accuracy 91.8%, cross entropy 0.270065
INFO:tensorflow:Step #28110: rate 0.000020, accuracy 91.8%, cross entropy 0.237221
INFO:tensorflow:Step #28120: rate 0.000020, accuracy 91.0%, cross entropy 0.249285
INFO:tensorflow:Step #28130: rate 0.000020, accuracy 93.8%, cross entropy 0.202427
INFO:tensorflow:Step #28140: rate 0.000020, accuracy 90.6%, cross entropy 0.264234
INFO:tensorflow:Step #28150: rate 0.000020, accuracy 88.7%, cross entropy 0.297617
INFO:tensorflow:Step #28160: rate 0.000020, accuracy 90.6%, cross entropy 0.234164
INFO:tensorflow:Step #28170: rate 0.000020, accuracy 89.8%, cross entropy 0.272148
INFO:tensorflow:Step #28180: rate 0.000020, accuracy 90.2%, cross entropy 0.255547
INFO:tensorflow:Step #28190: rate 0.000020, accuracy 94.5%, cross entropy 0.165432
INFO:tensorflow:Step #28200: rate 0.000020, accuracy 91.0%, cross entropy 0.278821
INFO:tensorflow:Step #28210: rate 0.000020, accuracy 93.4%, cross entropy 0.200844
INFO

INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 327   5  12   4   3   1   3  11   6   2  13]
 [  0   3 240   4   3   1   8   0   0   0   0   2]
 [  0   8   0 256   0   0   0   1   1   0   1   3]
 [  0   3   0   1 211   1   5   0   2  27   3   7]
 [  0   3   0  14   0 243   0   0   0   0   1   3]
 [  0   0   5   4   1   1 234   0   2   0   0   0]
 [  0  13   0   0   2   0   3 231   7   0   0   0]
 [  0   7   0   0   5   0   0   0 242   3   0   0]
 [  0   1   0   0  12   0   1   0  11 231   0   0]
 [  0   7   0   0   4   3   2   0   0   3 225   2]
 [  0   6   0  22   7   6   1   0   4   1   0 213]]
INFO:tensorflow:Step 29000: Validation accuracy = 89.5% (N=2964)
INFO:tensorflow:Step #29010: rate 0.000020, accuracy 94.1%, cross entropy 0.188830
INFO:tensorflow:Step #29020: rate 0.000020, accuracy 91.0%, cross entropy 0.307089
INFO:tensorflow:Step #29030: rate 0.000020, accuracy 92.2%, cross entropy 0.255639
INFO:tensorflow:Step #29040: rate 0.00

INFO:tensorflow:Step #29830: rate 0.000020, accuracy 89.8%, cross entropy 0.270928
INFO:tensorflow:Step #29840: rate 0.000020, accuracy 91.4%, cross entropy 0.250930
INFO:tensorflow:Step #29850: rate 0.000020, accuracy 92.2%, cross entropy 0.196437
INFO:tensorflow:Step #29860: rate 0.000020, accuracy 91.8%, cross entropy 0.214765
INFO:tensorflow:Step #29870: rate 0.000020, accuracy 91.8%, cross entropy 0.235199
INFO:tensorflow:Step #29880: rate 0.000020, accuracy 91.4%, cross entropy 0.283109
INFO:tensorflow:Step #29890: rate 0.000020, accuracy 93.0%, cross entropy 0.207688
INFO:tensorflow:Step #29900: rate 0.000020, accuracy 95.3%, cross entropy 0.131518
INFO:tensorflow:Step #29910: rate 0.000020, accuracy 91.8%, cross entropy 0.247824
INFO:tensorflow:Step #29920: rate 0.000020, accuracy 92.2%, cross entropy 0.234974
INFO:tensorflow:Step #29930: rate 0.000020, accuracy 92.2%, cross entropy 0.205660
INFO:tensorflow:Step #29940: rate 0.000020, accuracy 92.6%, cross entropy 0.240476
INFO

INFO:tensorflow:Step #30650: rate 0.000100, accuracy 93.4%, cross entropy 0.205839
INFO:tensorflow:Step #30660: rate 0.000100, accuracy 89.8%, cross entropy 0.286232
INFO:tensorflow:Step #30670: rate 0.000100, accuracy 90.6%, cross entropy 0.280010
INFO:tensorflow:Step #30680: rate 0.000100, accuracy 89.5%, cross entropy 0.319021
INFO:tensorflow:Step #30690: rate 0.000100, accuracy 91.8%, cross entropy 0.228640
INFO:tensorflow:Step #30700: rate 0.000100, accuracy 92.2%, cross entropy 0.240970
INFO:tensorflow:Step #30710: rate 0.000100, accuracy 93.4%, cross entropy 0.236200
INFO:tensorflow:Step #30720: rate 0.000100, accuracy 91.8%, cross entropy 0.212163
INFO:tensorflow:Step #30730: rate 0.000100, accuracy 93.0%, cross entropy 0.208456
INFO:tensorflow:Step #30740: rate 0.000100, accuracy 91.4%, cross entropy 0.201052
INFO:tensorflow:Step #30750: rate 0.000100, accuracy 92.6%, cross entropy 0.219865
INFO:tensorflow:Step #30760: rate 0.000100, accuracy 91.0%, cross entropy 0.280764
INFO

INFO:tensorflow:Step 31500: Validation accuracy = 89.1% (N=2964)
INFO:tensorflow:Step #31510: rate 0.000100, accuracy 91.8%, cross entropy 0.244883
INFO:tensorflow:Step #31520: rate 0.000100, accuracy 91.4%, cross entropy 0.233114
INFO:tensorflow:Step #31530: rate 0.000100, accuracy 91.0%, cross entropy 0.253694
INFO:tensorflow:Step #31540: rate 0.000100, accuracy 89.1%, cross entropy 0.308175
INFO:tensorflow:Step #31550: rate 0.000100, accuracy 90.2%, cross entropy 0.280843
INFO:tensorflow:Step #31560: rate 0.000100, accuracy 93.4%, cross entropy 0.165032
INFO:tensorflow:Step #31570: rate 0.000100, accuracy 91.0%, cross entropy 0.249514
INFO:tensorflow:Step #31580: rate 0.000100, accuracy 97.3%, cross entropy 0.108320
INFO:tensorflow:Step #31590: rate 0.000100, accuracy 92.6%, cross entropy 0.262707
INFO:tensorflow:Step #31600: rate 0.000100, accuracy 91.4%, cross entropy 0.244395
INFO:tensorflow:Step #31610: rate 0.000100, accuracy 94.1%, cross entropy 0.186544
INFO:tensorflow:Step #

INFO:tensorflow:Step #32410: rate 0.000100, accuracy 91.8%, cross entropy 0.217856
INFO:tensorflow:Step #32420: rate 0.000100, accuracy 92.2%, cross entropy 0.216665
INFO:tensorflow:Step #32430: rate 0.000100, accuracy 91.8%, cross entropy 0.248025
INFO:tensorflow:Step #32440: rate 0.000100, accuracy 87.5%, cross entropy 0.330760
INFO:tensorflow:Step #32450: rate 0.000100, accuracy 92.2%, cross entropy 0.212290
INFO:tensorflow:Step #32460: rate 0.000100, accuracy 93.0%, cross entropy 0.240226
INFO:tensorflow:Step #32470: rate 0.000100, accuracy 91.4%, cross entropy 0.235098
INFO:tensorflow:Step #32480: rate 0.000100, accuracy 91.4%, cross entropy 0.250392
INFO:tensorflow:Step #32490: rate 0.000100, accuracy 89.5%, cross entropy 0.303284
INFO:tensorflow:Step #32500: rate 0.000100, accuracy 90.6%, cross entropy 0.277088
INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 323   3  10   6   4   2   3  15   5   2  14]
 [  0   4 245   3   3   1   3   0

INFO:tensorflow:Step #33230: rate 0.000100, accuracy 86.7%, cross entropy 0.377164
INFO:tensorflow:Step #33240: rate 0.000100, accuracy 90.6%, cross entropy 0.259690
INFO:tensorflow:Step #33250: rate 0.000100, accuracy 90.6%, cross entropy 0.259887
INFO:tensorflow:Step #33260: rate 0.000100, accuracy 91.4%, cross entropy 0.200483
INFO:tensorflow:Step #33270: rate 0.000100, accuracy 94.5%, cross entropy 0.147536
INFO:tensorflow:Step #33280: rate 0.000100, accuracy 94.1%, cross entropy 0.181558
INFO:tensorflow:Step #33290: rate 0.000100, accuracy 91.4%, cross entropy 0.266020
INFO:tensorflow:Step #33300: rate 0.000100, accuracy 91.8%, cross entropy 0.241006
INFO:tensorflow:Step #33310: rate 0.000100, accuracy 90.6%, cross entropy 0.275932
INFO:tensorflow:Step #33320: rate 0.000100, accuracy 90.6%, cross entropy 0.297393
INFO:tensorflow:Step #33330: rate 0.000100, accuracy 91.8%, cross entropy 0.223571
INFO:tensorflow:Step #33340: rate 0.000100, accuracy 93.4%, cross entropy 0.202897
INFO

INFO:tensorflow:Step #34050: rate 0.000100, accuracy 91.0%, cross entropy 0.226350
INFO:tensorflow:Step #34060: rate 0.000100, accuracy 91.8%, cross entropy 0.253531
INFO:tensorflow:Step #34070: rate 0.000100, accuracy 92.2%, cross entropy 0.226720
INFO:tensorflow:Step #34080: rate 0.000100, accuracy 93.0%, cross entropy 0.247602
INFO:tensorflow:Step #34090: rate 0.000100, accuracy 91.4%, cross entropy 0.232108
INFO:tensorflow:Step #34100: rate 0.000100, accuracy 91.4%, cross entropy 0.229102
INFO:tensorflow:Step #34110: rate 0.000100, accuracy 93.4%, cross entropy 0.221333
INFO:tensorflow:Step #34120: rate 0.000100, accuracy 91.8%, cross entropy 0.227174
INFO:tensorflow:Step #34130: rate 0.000100, accuracy 89.5%, cross entropy 0.317977
INFO:tensorflow:Step #34140: rate 0.000100, accuracy 92.6%, cross entropy 0.228082
INFO:tensorflow:Step #34150: rate 0.000100, accuracy 89.5%, cross entropy 0.278266
INFO:tensorflow:Step #34160: rate 0.000100, accuracy 92.6%, cross entropy 0.223551
INFO

INFO:tensorflow:Step #34960: rate 0.000100, accuracy 94.1%, cross entropy 0.196384
INFO:tensorflow:Step #34970: rate 0.000100, accuracy 92.2%, cross entropy 0.252275
INFO:tensorflow:Step #34980: rate 0.000100, accuracy 94.9%, cross entropy 0.171290
INFO:tensorflow:Step #34990: rate 0.000100, accuracy 93.8%, cross entropy 0.219306
INFO:tensorflow:Step #35000: rate 0.000100, accuracy 89.5%, cross entropy 0.247544
INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 311   7  18   4   5   1   3  19   4   2  13]
 [  0   2 244   5   3   1   3   0   1   0   0   2]
 [  0   7   0 251   0   2   0   1   1   1   1   6]
 [  0   5   1   2 210   0   2   1   5  23   5   6]
 [  0   2   0  13   0 245   0   0   0   0   1   3]
 [  0   1   9   5   1   1 228   0   2   0   0   0]
 [  0  15   0   2   0   0   3 226   9   0   0   1]
 [  0   3   0   1   0   1   0   0 245   3   0   4]
 [  0   1   0   0   9   0   1   0  17 226   1   1]
 [  0   9   1   1   4   4   1   0   0   

INFO:tensorflow:Step #35780: rate 0.000100, accuracy 92.2%, cross entropy 0.251289
INFO:tensorflow:Step #35790: rate 0.000100, accuracy 91.8%, cross entropy 0.280560
INFO:tensorflow:Step #35800: rate 0.000100, accuracy 91.8%, cross entropy 0.234146
INFO:tensorflow:Step #35810: rate 0.000100, accuracy 89.8%, cross entropy 0.259602
INFO:tensorflow:Step #35820: rate 0.000100, accuracy 92.2%, cross entropy 0.212422
INFO:tensorflow:Step #35830: rate 0.000100, accuracy 91.8%, cross entropy 0.246438
INFO:tensorflow:Step #35840: rate 0.000100, accuracy 94.1%, cross entropy 0.189277
INFO:tensorflow:Step #35850: rate 0.000100, accuracy 93.8%, cross entropy 0.204628
INFO:tensorflow:Step #35860: rate 0.000100, accuracy 92.2%, cross entropy 0.218505
INFO:tensorflow:Step #35870: rate 0.000100, accuracy 91.8%, cross entropy 0.235508
INFO:tensorflow:Step #35880: rate 0.000100, accuracy 95.3%, cross entropy 0.153858
INFO:tensorflow:Step #35890: rate 0.000100, accuracy 91.8%, cross entropy 0.266867
INFO

INFO:tensorflow:Step #36600: rate 0.000100, accuracy 93.4%, cross entropy 0.184941
INFO:tensorflow:Step #36610: rate 0.000100, accuracy 90.2%, cross entropy 0.284262
INFO:tensorflow:Step #36620: rate 0.000100, accuracy 91.8%, cross entropy 0.249849
INFO:tensorflow:Step #36630: rate 0.000100, accuracy 93.8%, cross entropy 0.185028
INFO:tensorflow:Step #36640: rate 0.000100, accuracy 92.2%, cross entropy 0.197143
INFO:tensorflow:Step #36650: rate 0.000100, accuracy 89.8%, cross entropy 0.229386
INFO:tensorflow:Step #36660: rate 0.000100, accuracy 94.1%, cross entropy 0.141169
INFO:tensorflow:Step #36670: rate 0.000100, accuracy 94.5%, cross entropy 0.151986
INFO:tensorflow:Step #36680: rate 0.000100, accuracy 91.8%, cross entropy 0.217178
INFO:tensorflow:Step #36690: rate 0.000100, accuracy 91.4%, cross entropy 0.211697
INFO:tensorflow:Step #36700: rate 0.000100, accuracy 92.6%, cross entropy 0.238311
INFO:tensorflow:Step #36710: rate 0.000100, accuracy 92.6%, cross entropy 0.217338
INFO

INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 319   6  11   2   7   3   3  17   5   2  12]
 [  0   1 240   7   3   2   5   0   0   0   0   3]
 [  0   7   0 255   0   0   0   1   1   0   2   4]
 [  0   4   0   1 216   0   4   0   1  20   5   9]
 [  0   3   0  10   0 246   0   0   1   0   1   3]
 [  0   2   7   4   1   1 229   1   2   0   0   0]
 [  0  14   0   0   3   0   4 229   6   0   0   0]
 [  0   4   0   0   3   1   0   0 245   2   0   2]
 [  0   0   0   0  11   0   1   0  15 225   2   2]
 [  0   6   0   1   3   6   2   0   0   3 223   2]
 [  0   7   0  23   5   3   1   0   6   1   0 214]]
INFO:tensorflow:Step 37500: Validation accuracy = 89.1% (N=2964)
INFO:tensorflow:Step #37510: rate 0.000100, accuracy 93.8%, cross entropy 0.216383
INFO:tensorflow:Step #37520: rate 0.000100, accuracy 91.4%, cross entropy 0.253909
INFO:tensorflow:Step #37530: rate 0.000100, accuracy 89.8%, cross entropy 0.303646
INFO:tensorflow:Step #37540: rate 0.00

INFO:tensorflow:Step #38330: rate 0.000100, accuracy 93.0%, cross entropy 0.214260
INFO:tensorflow:Step #38340: rate 0.000100, accuracy 93.0%, cross entropy 0.211391
INFO:tensorflow:Step #38350: rate 0.000100, accuracy 93.0%, cross entropy 0.215907
INFO:tensorflow:Step #38360: rate 0.000100, accuracy 94.1%, cross entropy 0.168525
INFO:tensorflow:Step #38370: rate 0.000100, accuracy 92.6%, cross entropy 0.219292
INFO:tensorflow:Step #38380: rate 0.000100, accuracy 92.2%, cross entropy 0.265287
INFO:tensorflow:Step #38390: rate 0.000100, accuracy 89.5%, cross entropy 0.314646
INFO:tensorflow:Step #38400: rate 0.000100, accuracy 91.8%, cross entropy 0.229432
INFO:tensorflow:Step #38410: rate 0.000100, accuracy 91.8%, cross entropy 0.246518
INFO:tensorflow:Step #38420: rate 0.000100, accuracy 93.4%, cross entropy 0.220080
INFO:tensorflow:Step #38430: rate 0.000100, accuracy 93.8%, cross entropy 0.178464
INFO:tensorflow:Step #38440: rate 0.000100, accuracy 92.6%, cross entropy 0.217207
INFO

INFO:tensorflow:Step #39150: rate 0.000100, accuracy 91.8%, cross entropy 0.223248
INFO:tensorflow:Step #39160: rate 0.000100, accuracy 92.2%, cross entropy 0.198822
INFO:tensorflow:Step #39170: rate 0.000100, accuracy 89.8%, cross entropy 0.281224
INFO:tensorflow:Step #39180: rate 0.000100, accuracy 89.8%, cross entropy 0.316734
INFO:tensorflow:Step #39190: rate 0.000100, accuracy 91.4%, cross entropy 0.249991
INFO:tensorflow:Step #39200: rate 0.000100, accuracy 93.0%, cross entropy 0.213423
INFO:tensorflow:Step #39210: rate 0.000100, accuracy 93.4%, cross entropy 0.231880
INFO:tensorflow:Step #39220: rate 0.000100, accuracy 92.6%, cross entropy 0.195419
INFO:tensorflow:Step #39230: rate 0.000100, accuracy 92.6%, cross entropy 0.235489
INFO:tensorflow:Step #39240: rate 0.000100, accuracy 91.0%, cross entropy 0.245091
INFO:tensorflow:Step #39250: rate 0.000100, accuracy 93.4%, cross entropy 0.173933
INFO:tensorflow:Step #39260: rate 0.000100, accuracy 93.4%, cross entropy 0.222355
INFO

INFO:tensorflow:Step 40000: Validation accuracy = 89.1% (N=2964)
INFO:tensorflow:Step #40010: rate 0.000100, accuracy 93.0%, cross entropy 0.215065
INFO:tensorflow:Step #40020: rate 0.000100, accuracy 93.0%, cross entropy 0.203889
INFO:tensorflow:Step #40030: rate 0.000100, accuracy 93.8%, cross entropy 0.172170
INFO:tensorflow:Step #40040: rate 0.000100, accuracy 90.2%, cross entropy 0.237522
INFO:tensorflow:Step #40050: rate 0.000100, accuracy 93.4%, cross entropy 0.170847
INFO:tensorflow:Step #40060: rate 0.000100, accuracy 91.4%, cross entropy 0.268744
INFO:tensorflow:Step #40070: rate 0.000100, accuracy 91.0%, cross entropy 0.237003
INFO:tensorflow:Step #40080: rate 0.000100, accuracy 90.2%, cross entropy 0.256736
INFO:tensorflow:Step #40090: rate 0.000100, accuracy 89.8%, cross entropy 0.265723
INFO:tensorflow:Step #40100: rate 0.000100, accuracy 93.8%, cross entropy 0.192051
INFO:tensorflow:Step #40110: rate 0.000100, accuracy 91.0%, cross entropy 0.234418
INFO:tensorflow:Step #

INFO:tensorflow:Step #40910: rate 0.000100, accuracy 93.0%, cross entropy 0.184985
INFO:tensorflow:Step #40920: rate 0.000100, accuracy 93.0%, cross entropy 0.196491
INFO:tensorflow:Step #40930: rate 0.000100, accuracy 92.6%, cross entropy 0.195089
INFO:tensorflow:Step #40940: rate 0.000100, accuracy 93.0%, cross entropy 0.202784
INFO:tensorflow:Step #40950: rate 0.000100, accuracy 93.8%, cross entropy 0.213342
INFO:tensorflow:Step #40960: rate 0.000100, accuracy 93.0%, cross entropy 0.174509
INFO:tensorflow:Step #40970: rate 0.000100, accuracy 94.5%, cross entropy 0.162667
INFO:tensorflow:Step #40980: rate 0.000100, accuracy 89.5%, cross entropy 0.289169
INFO:tensorflow:Step #40990: rate 0.000100, accuracy 93.0%, cross entropy 0.223626
INFO:tensorflow:Step #41000: rate 0.000100, accuracy 93.4%, cross entropy 0.209351
INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 325   4   8   2   6   2   5  16   6   1  12]
 [  0   1 242   5   2   1   6   1

INFO:tensorflow:Step #41730: rate 0.000100, accuracy 90.6%, cross entropy 0.268300
INFO:tensorflow:Step #41740: rate 0.000100, accuracy 90.2%, cross entropy 0.260087
INFO:tensorflow:Step #41750: rate 0.000100, accuracy 91.0%, cross entropy 0.213639
INFO:tensorflow:Step #41760: rate 0.000100, accuracy 89.5%, cross entropy 0.261415
INFO:tensorflow:Step #41770: rate 0.000100, accuracy 93.4%, cross entropy 0.163418
INFO:tensorflow:Step #41780: rate 0.000100, accuracy 92.6%, cross entropy 0.181429
INFO:tensorflow:Step #41790: rate 0.000100, accuracy 92.2%, cross entropy 0.217874
INFO:tensorflow:Step #41800: rate 0.000100, accuracy 93.8%, cross entropy 0.192693
INFO:tensorflow:Step #41810: rate 0.000100, accuracy 94.1%, cross entropy 0.164707
INFO:tensorflow:Step #41820: rate 0.000100, accuracy 95.7%, cross entropy 0.132479
INFO:tensorflow:Step #41830: rate 0.000100, accuracy 94.1%, cross entropy 0.191737
INFO:tensorflow:Step #41840: rate 0.000100, accuracy 93.4%, cross entropy 0.151760
INFO

INFO:tensorflow:Step #42550: rate 0.000100, accuracy 94.5%, cross entropy 0.166429
INFO:tensorflow:Step #42560: rate 0.000100, accuracy 93.0%, cross entropy 0.247013
INFO:tensorflow:Step #42570: rate 0.000100, accuracy 96.1%, cross entropy 0.150452
INFO:tensorflow:Step #42580: rate 0.000100, accuracy 93.4%, cross entropy 0.250964
INFO:tensorflow:Step #42590: rate 0.000100, accuracy 93.4%, cross entropy 0.181327
INFO:tensorflow:Step #42600: rate 0.000100, accuracy 91.0%, cross entropy 0.249382
INFO:tensorflow:Step #42610: rate 0.000100, accuracy 92.6%, cross entropy 0.197777
INFO:tensorflow:Step #42620: rate 0.000100, accuracy 91.0%, cross entropy 0.275685
INFO:tensorflow:Step #42630: rate 0.000100, accuracy 95.3%, cross entropy 0.140385
INFO:tensorflow:Step #42640: rate 0.000100, accuracy 89.8%, cross entropy 0.298773
INFO:tensorflow:Step #42650: rate 0.000100, accuracy 93.0%, cross entropy 0.227295
INFO:tensorflow:Step #42660: rate 0.000100, accuracy 93.8%, cross entropy 0.190179
INFO

INFO:tensorflow:Step #43460: rate 0.000100, accuracy 93.0%, cross entropy 0.179603
INFO:tensorflow:Step #43470: rate 0.000100, accuracy 93.0%, cross entropy 0.180645
INFO:tensorflow:Step #43480: rate 0.000100, accuracy 95.3%, cross entropy 0.177554
INFO:tensorflow:Step #43490: rate 0.000100, accuracy 92.2%, cross entropy 0.214326
INFO:tensorflow:Step #43500: rate 0.000100, accuracy 93.8%, cross entropy 0.170912
INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 327   4  12   4   2   2   4  13   5   1  13]
 [  0   1 241   5   3   0   6   1   1   0   0   3]
 [  0   8   0 256   0   0   0   1   1   0   1   3]
 [  0   5   0   1 216   0   3   0   5  22   3   5]
 [  0   2   0  10   0 246   0   0   0   0   1   5]
 [  0   0   7   4   1   1 232   0   2   0   0   0]
 [  0  20   1   1   2   0   2 226   4   0   0   0]
 [  0   4   0   0   3   1   1   0 245   2   0   1]
 [  0   1   0   0  12   0   1   0  16 226   0   0]
 [  0   8   0   1   4   3   2   0   0   

INFO:tensorflow:Step #44280: rate 0.000100, accuracy 94.9%, cross entropy 0.165595
INFO:tensorflow:Step #44290: rate 0.000100, accuracy 93.0%, cross entropy 0.208911
INFO:tensorflow:Step #44300: rate 0.000100, accuracy 90.6%, cross entropy 0.262554
INFO:tensorflow:Step #44310: rate 0.000100, accuracy 89.8%, cross entropy 0.261268
INFO:tensorflow:Step #44320: rate 0.000100, accuracy 94.5%, cross entropy 0.188912
INFO:tensorflow:Step #44330: rate 0.000100, accuracy 93.0%, cross entropy 0.193583
INFO:tensorflow:Step #44340: rate 0.000100, accuracy 92.6%, cross entropy 0.189590
INFO:tensorflow:Step #44350: rate 0.000100, accuracy 94.5%, cross entropy 0.146044
INFO:tensorflow:Step #44360: rate 0.000100, accuracy 90.6%, cross entropy 0.262240
INFO:tensorflow:Step #44370: rate 0.000100, accuracy 93.4%, cross entropy 0.208699
INFO:tensorflow:Step #44380: rate 0.000100, accuracy 92.6%, cross entropy 0.219602
INFO:tensorflow:Step #44390: rate 0.000100, accuracy 95.3%, cross entropy 0.155995
INFO

INFO:tensorflow:Step #45100: rate 0.000020, accuracy 92.2%, cross entropy 0.235509
INFO:tensorflow:Step #45110: rate 0.000020, accuracy 93.4%, cross entropy 0.193881
INFO:tensorflow:Step #45120: rate 0.000020, accuracy 93.0%, cross entropy 0.205841
INFO:tensorflow:Step #45130: rate 0.000020, accuracy 92.6%, cross entropy 0.196358
INFO:tensorflow:Step #45140: rate 0.000020, accuracy 93.4%, cross entropy 0.209291
INFO:tensorflow:Step #45150: rate 0.000020, accuracy 93.8%, cross entropy 0.174706
INFO:tensorflow:Step #45160: rate 0.000020, accuracy 92.2%, cross entropy 0.229557
INFO:tensorflow:Step #45170: rate 0.000020, accuracy 92.2%, cross entropy 0.180234
INFO:tensorflow:Step #45180: rate 0.000020, accuracy 92.2%, cross entropy 0.205824
INFO:tensorflow:Step #45190: rate 0.000020, accuracy 93.0%, cross entropy 0.234172
INFO:tensorflow:Step #45200: rate 0.000020, accuracy 90.2%, cross entropy 0.253499
INFO:tensorflow:Step #45210: rate 0.000020, accuracy 94.5%, cross entropy 0.176979
INFO

INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 322   4  11   4   6   3   4  14   5   0  14]
 [  0   2 239   7   3   0   7   1   0   0   0   2]
 [  0   8   0 255   0   1   0   1   1   0   1   3]
 [  0   5   0   1 215   0   2   1   4  21   4   7]
 [  0   1   0  12   0 246   0   0   0   0   1   4]
 [  0   0   8   4   1   1 231   0   2   0   0   0]
 [  0  12   1   1   2   0   3 232   5   0   0   0]
 [  0   5   0   0   5   2   0   0 242   3   0   0]
 [  0   2   0   0  12   0   1   0  13 228   0   0]
 [  0   4   0   1   5   3   2   0   0   3 223   5]
 [  0   6   0  20   4   4   0   1   6   1   0 218]]
INFO:tensorflow:Step 46000: Validation accuracy = 89.4% (N=2964)
INFO:tensorflow:Step #46010: rate 0.000020, accuracy 91.8%, cross entropy 0.218312
INFO:tensorflow:Step #46020: rate 0.000020, accuracy 91.0%, cross entropy 0.236123
INFO:tensorflow:Step #46030: rate 0.000020, accuracy 90.2%, cross entropy 0.286339
INFO:tensorflow:Step #46040: rate 0.00

INFO:tensorflow:Step #46830: rate 0.000020, accuracy 95.7%, cross entropy 0.151808
INFO:tensorflow:Step #46840: rate 0.000020, accuracy 92.6%, cross entropy 0.196171
INFO:tensorflow:Step #46850: rate 0.000020, accuracy 91.4%, cross entropy 0.197464
INFO:tensorflow:Step #46860: rate 0.000020, accuracy 90.6%, cross entropy 0.254192
INFO:tensorflow:Step #46870: rate 0.000020, accuracy 91.0%, cross entropy 0.251648
INFO:tensorflow:Step #46880: rate 0.000020, accuracy 93.0%, cross entropy 0.201916
INFO:tensorflow:Step #46890: rate 0.000020, accuracy 92.2%, cross entropy 0.207883
INFO:tensorflow:Step #46900: rate 0.000020, accuracy 94.9%, cross entropy 0.195092
INFO:tensorflow:Step #46910: rate 0.000020, accuracy 94.1%, cross entropy 0.178066
INFO:tensorflow:Step #46920: rate 0.000020, accuracy 93.4%, cross entropy 0.160971
INFO:tensorflow:Step #46930: rate 0.000020, accuracy 92.2%, cross entropy 0.236752
INFO:tensorflow:Step #46940: rate 0.000020, accuracy 92.6%, cross entropy 0.189259
INFO

INFO:tensorflow:Step #47650: rate 0.000020, accuracy 94.5%, cross entropy 0.156762
INFO:tensorflow:Step #47660: rate 0.000020, accuracy 93.8%, cross entropy 0.158743
INFO:tensorflow:Step #47670: rate 0.000020, accuracy 93.4%, cross entropy 0.185700
INFO:tensorflow:Step #47680: rate 0.000020, accuracy 94.1%, cross entropy 0.167218
INFO:tensorflow:Step #47690: rate 0.000020, accuracy 93.4%, cross entropy 0.188644
INFO:tensorflow:Step #47700: rate 0.000020, accuracy 95.7%, cross entropy 0.154615
INFO:tensorflow:Step #47710: rate 0.000020, accuracy 91.4%, cross entropy 0.226166
INFO:tensorflow:Step #47720: rate 0.000020, accuracy 92.6%, cross entropy 0.208918
INFO:tensorflow:Step #47730: rate 0.000020, accuracy 94.1%, cross entropy 0.169923
INFO:tensorflow:Step #47740: rate 0.000020, accuracy 92.6%, cross entropy 0.201024
INFO:tensorflow:Step #47750: rate 0.000020, accuracy 93.0%, cross entropy 0.176430
INFO:tensorflow:Step #47760: rate 0.000020, accuracy 94.1%, cross entropy 0.187266
INFO

INFO:tensorflow:Step 48500: Validation accuracy = 89.0% (N=2964)
INFO:tensorflow:Step #48510: rate 0.000020, accuracy 96.5%, cross entropy 0.104558
INFO:tensorflow:Step #48520: rate 0.000020, accuracy 91.4%, cross entropy 0.214003
INFO:tensorflow:Step #48530: rate 0.000020, accuracy 94.9%, cross entropy 0.142391
INFO:tensorflow:Step #48540: rate 0.000020, accuracy 93.8%, cross entropy 0.163075
INFO:tensorflow:Step #48550: rate 0.000020, accuracy 93.4%, cross entropy 0.178246
INFO:tensorflow:Step #48560: rate 0.000020, accuracy 95.3%, cross entropy 0.140290
INFO:tensorflow:Step #48570: rate 0.000020, accuracy 91.4%, cross entropy 0.294631
INFO:tensorflow:Step #48580: rate 0.000020, accuracy 94.5%, cross entropy 0.175694
INFO:tensorflow:Step #48590: rate 0.000020, accuracy 92.2%, cross entropy 0.203508
INFO:tensorflow:Step #48600: rate 0.000020, accuracy 94.9%, cross entropy 0.176591
INFO:tensorflow:Step #48610: rate 0.000020, accuracy 94.5%, cross entropy 0.169270
INFO:tensorflow:Step #

INFO:tensorflow:Step #49410: rate 0.000020, accuracy 92.2%, cross entropy 0.265703
INFO:tensorflow:Step #49420: rate 0.000020, accuracy 91.4%, cross entropy 0.243761
INFO:tensorflow:Step #49430: rate 0.000020, accuracy 92.6%, cross entropy 0.222590
INFO:tensorflow:Step #49440: rate 0.000020, accuracy 93.0%, cross entropy 0.205923
INFO:tensorflow:Step #49450: rate 0.000020, accuracy 93.8%, cross entropy 0.209119
INFO:tensorflow:Step #49460: rate 0.000020, accuracy 93.0%, cross entropy 0.197979
INFO:tensorflow:Step #49470: rate 0.000020, accuracy 95.7%, cross entropy 0.140304
INFO:tensorflow:Step #49480: rate 0.000020, accuracy 93.0%, cross entropy 0.200992
INFO:tensorflow:Step #49490: rate 0.000020, accuracy 90.6%, cross entropy 0.237526
INFO:tensorflow:Step #49500: rate 0.000020, accuracy 93.8%, cross entropy 0.206468
INFO:tensorflow:Confusion Matrix:
 [[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 320   3  15   4   3   3   5  17   5   0  12]
 [  0   1 239   8   3   1   6   1

TypeError: expected str, bytes or os.PathLike object, not NoneType